import { Typography } from '@mui/material';
import LegalPageLayout, { type LegalSection } from '@/components/Legal/LegalPageLayout';

const P = ({ children }) => <Typography>{children}</Typography>;

export default function TermsOfUse() {
  const sections: LegalSection[] = [
    { id: 'objet', title: '1. Objet et acceptation', content: <P>Les présentes conditions encadrent l’accès à MealMosaic et l’utilisation de ses recettes, profils, favoris, commentaires, cours, fonctions premium et suggestions d’IA. La création d’un compte vaut acceptation de la version applicable des présentes CGU.</P> },
    { id: 'compte', title: '2. Compte utilisateur', content: <P>L’utilisateur fournit des informations exactes, protège ses identifiants et informe [À COMPLÉTER — contact] en cas d’accès non autorisé. Il est responsable des actions réalisées depuis son compte. Certaines informations de profil et contributions sont publiques, comme indiqué dans la politique de confidentialité.</P> },
    { id: 'usage', title: '3. Règles d’utilisation', content: <P>Il est interdit de publier un contenu illégal, trompeur, haineux, dangereux, contrefaisant, portant atteinte à la vie privée, contenant un logiciel malveillant ou perturbant le service. L’extraction automatisée, le contournement des contrôles d’accès et l’utilisation frauduleuse des offres sont interdits.</P> },
    { id: 'contenus', title: '4. Contenus publiés par les utilisateurs', content: <P>L’utilisateur conserve ses droits sur ses recettes, images, commentaires, cours et vidéos. Il garantit disposer des droits nécessaires. Il accorde à [À COMPLÉTER — éditeur] une licence non exclusive, gratuite et mondiale, limitée à la durée de publication, permettant d’héberger, reproduire techniquement et afficher ces contenus afin de fournir MealMosaic. Le contenu peut être retiré lorsqu’il enfreint les présentes conditions ou la loi.</P> },
    { id: 'premium', title: '5. Accès premium et rôles', content: <P>Certaines recettes et certains cours sont réservés aux membres disposant du rôle ou de l’abonnement requis. Les conditions financières et de renouvellement relèvent des Conditions générales de vente. Toute tentative de contourner ces restrictions peut entraîner la suspension du compte.</P> },
    { id: 'ia', title: '6. Suggestions générées par IA', content: <P>Les suggestions sont produites automatiquement à partir des recettes au moyen d’un prestataire tiers. Elles peuvent être inexactes, incomplètes ou inadaptées. Elles ne constituent ni un conseil médical ou nutritionnel, ni une garantie de résultat. L’utilisateur doit les vérifier avant utilisation.</P> },
    { id: 'securite-alimentaire', title: '7. Sécurité alimentaire et allergies', content: <P>Les recettes proviennent notamment des utilisateurs. MealMosaic ne garantit pas l’absence d’allergènes, l’exactitude des quantités, les temps de cuisson ou la conformité sanitaire. Chaque utilisateur doit adapter les recettes à sa santé, vérifier les ingrédients et respecter les règles de conservation et de cuisson.</P> },
    { id: 'disponibilite', title: '8. Disponibilité et responsabilité', content: <P>Le projet peut être modifié, interrompu ou indisponible, notamment pour maintenance. Dans les limites autorisées par la loi, l’éditeur n’est pas responsable des contenus publiés par les utilisateurs, des décisions prises sur la base d’une suggestion d’IA ou d’un dommage résultant d’un usage contraire aux présentes conditions. Les garanties légales impératives restent applicables.</P> },
    { id: 'suspension', title: '9. Suspension, suppression et signalement', content: <P>L’éditeur peut masquer un contenu ou suspendre un compte en cas de violation, de risque de sécurité ou d’obligation légale, avec information de l’utilisateur lorsque cela est possible. Pour signaler un contenu ou demander la fermeture d’un compte, contactez [À COMPLÉTER — adresse électronique]. La suppression en libre-service n’est pas encore disponible dans cette version étudiante.</P> },
    { id: 'droit', title: '10. Droit applicable', content: <P>Les présentes conditions sont soumises au droit français. Les règles impératives protégeant les consommateurs et les voies amiables obligatoires demeurent applicables. Juridiction compétente et procédure de contact : [À COMPLÉTER avant mise en production].</P> },
  ];

  return <LegalPageLayout title="Conditions générales d’utilisation" description='Règles applicables à l’utilisation du site, des comptes et des contenus MealMosaic.' sections={sections} />;
}
