import { Alert, Typography } from '@mui/material';
import LegalPageLayout, { type LegalSection } from '@/components/Legal/LegalPageLayout';

const P = ({ children }) => <Typography>{children}</Typography>;

export default function TermsOfSale() {
  const sections: LegalSection[] = [
    { id: 'avertissement', title: '1. Avertissement — démonstration', content: <Alert severity='error'>Ces CGV sont un modèle pour projet étudiant. Elles ne doivent pas accompagner une vente réelle tant que l’identité du vendeur, les prix définitifs, la fiscalité, la médiation, le droit de rétractation et une fonctionnalité de résiliation électronique ne sont pas finalisés et validés.</Alert> },
    { id: 'vendeur', title: '2. Vendeur et contact', content: <P>[À COMPLÉTER — nom ou raison sociale, forme juridique, capital, RCS/RNE, SIREN/SIRET, numéro de TVA, adresse, téléphone et adresse électronique]. Service client : [À COMPLÉTER — coordonnées et horaires].</P> },
    { id: 'offres', title: '3. Offres et services', content: <P>MealMosaic présente une offre gratuite « Home Cook » et des abonnements « Sous Chef » et « Master Chef ». Selon l’offre, l’utilisateur peut accéder aux recettes premium, créer des recettes ou obtenir un rôle de chef. Le contenu exact, les prérequis techniques et les éventuelles limitations sont ceux affichés avant la commande.</P> },
    { id: 'prix', title: '4. Prix et facturation', content: <P>Le prix total, la devise, les taxes applicables et la périodicité mensuelle, semestrielle ou annuelle sont affichés dans le récapitulatif avant paiement. Les montants actuellement visibles sont des données de démonstration à confirmer : [À COMPLÉTER — grille tarifaire TTC et date d’effet]. Aucun montant ne doit être débité en production tant que ces informations ne sont pas finalisées.</P> },
    { id: 'commande', title: '5. Commande et acceptation', content: <P>L’utilisateur sélectionne une formule et une périodicité, vérifie le prix puis accepte expressément les présentes CGV avant d’être redirigé vers Stripe. La commande n’est définitive qu’après confirmation du paiement. Une confirmation est envoyée à l’adresse du compte et les éléments de commande sont conservés selon les durées légales applicables.</P> },
    { id: 'paiement', title: '6. Paiement et activation', content: <P>Le paiement est traité par Stripe. MealMosaic ne collecte pas le numéro complet de carte. L’accès payant est activé après confirmation du paiement et peut être suspendu en cas d’échec, d’impayé, de fraude ou d’annulation. Moyens de paiement, délais d’activation et procédure en cas d’erreur : [À COMPLÉTER].</P> },
    { id: 'renouvellement', title: '7. Durée et renouvellement', content: <P>L’abonnement est renouvelé automatiquement à chaque période sélectionnée jusqu’à sa résiliation. Avant une vente réelle, le parcours doit indiquer clairement la date ou fréquence de prélèvement, les règles de modification de prix et les informations légales relatives à la reconduction : [À COMPLÉTER].</P> },
    { id: 'resiliation', title: '8. Résiliation', content: <P>La gestion d’abonnement n’est pas opérationnelle dans cette version étudiante. Pour une mise en production, une fonctionnalité gratuite de résiliation électronique clairement identifiée doit être disponible et ses étapes décrites ici : [À COMPLÉTER — date d’effet, conséquences sur l’accès, remboursement éventuel et contact]. La mention « résiliable à tout moment » ne doit pas être utilisée avant sa mise en place.</P> },
    { id: 'retractation', title: '9. Droit de rétractation', content: <P>Le régime applicable dépend de la qualification exacte du service numérique et du moment où son exécution commence. Avant toute vente, préciser le délai de quatorze jours, le formulaire type, l’adresse d’envoi et, si l’accès commence immédiatement, recueillir séparément toute demande d’exécution anticipée et reconnaissance de perte du droit exigées par la loi : [À COMPLÉTER après validation juridique].</P> },
    { id: 'garanties', title: '10. Garanties et responsabilité', content: <P>Les garanties légales applicables aux services numériques restent dues. Procédure de mise en conformité, durée des mises à jour nécessaires, assistance technique et limites contractuelles licites : [À COMPLÉTER]. Aucune clause ne limite les droits impératifs du consommateur.</P> },
    { id: 'reclamations', title: '11. Réclamations et médiation', content: <P>Une réclamation doit d’abord être adressée à [À COMPLÉTER — service client]. En l’absence de solution amiable, le consommateur peut saisir gratuitement [À COMPLÉTER — médiateur de la consommation, adresse et site internet] après avoir suivi la procédure préalable requise. La plateforme européenne de règlement en ligne ayant cessé ses activités, aucune adresse obsolète ne doit être ajoutée.</P> },
    { id: 'droit', title: '12. Droit applicable et preuve', content: <P>Le contrat est soumis au droit français, sans priver le consommateur des protections impératives de son pays de résidence. Les enregistrements électroniques de la commande, de l’acceptation et des paiements peuvent servir de preuve dans les conditions prévues par la loi. Tribunal compétent et durée d’archivage : [À COMPLÉTER].</P> },
  ];

  return <LegalPageLayout title='Conditions générales de vente et d’abonnement' description='Informations contractuelles applicables aux offres payantes MealMosaic.' sections={sections} />;
}
