import { useTranslation } from 'react-i18next';
import { Alert, Typography } from '@mui/material';
import LegalPageLayout, { type LegalSection } from '@/components/Legal/LegalPageLayout';

const P = ({ children }) => <Typography>{children}</Typography>;

export default function TermsOfSale() {
  const { t } = useTranslation();
  const sections: LegalSection[] = [
    { id: 'avertissement', title: t("1. Warning — demonstration"), content: <Alert severity='error'>{t("These Terms of Sale are a template for a student project. They must not accompany a real sale until the seller’s identity, final prices, taxation, mediation, withdrawal rights, and an electronic cancellation feature have been finalized and validated.")}</Alert> },
    { id: 'vendeur', title: t("2. Seller and contact"), content: <P>{t("[TO COMPLETE — name or business name, legal form, share capital, RCS/RNE, SIREN/SIRET, VAT number, address, telephone number, and email address]. Customer service: [TO COMPLETE — contact details and opening hours].")}</P> },
    { id: 'offres', title: t("3. Offers and services"), content: <P>{t("MealMosaic offers a free “Home Cook” plan and “Sous Chef” and “Master Chef” subscriptions. Depending on the plan, users may access premium recipes, create recipes, or obtain a chef role. The exact content, technical requirements, and any limitations are those displayed before ordering.")}</P> },
    { id: 'prix', title: t("4. Prices and billing"), content: <P>{t("The total price, currency, applicable taxes, and monthly, six-monthly, or annual billing cycle are shown in the summary before payment. The amounts currently displayed are demonstration data to be confirmed: [TO COMPLETE — tax-inclusive price list and effective date]. No amount must be charged in production until this information has been finalized.")}</P> },
    { id: 'commande', title: t("5. Ordering and acceptance"), content: <P>{t("Users select a plan and billing cycle, check the price, and expressly accept these Terms of Sale before being redirected to Stripe. The order becomes final only after payment confirmation. A confirmation is sent to the account’s email address, and order information is retained for the applicable statutory periods.")}</P> },
    { id: 'paiement', title: t("6. Payment and activation"), content: <P>{t("Payment is processed by Stripe. MealMosaic does not collect full card numbers. Paid access is activated after payment confirmation and may be suspended in the event of payment failure, non-payment, fraud, or cancellation. Payment methods, activation times, and error-handling procedure: [TO COMPLETE].")}</P> },
    { id: 'renouvellement', title: t("7. Duration and renewal"), content: <P>{t("The subscription renews automatically for each selected billing period until cancellation. Before any real sale, the process must clearly state the payment date or frequency, price change rules, and statutory renewal information: [TO COMPLETE].")}</P> },
    { id: 'resiliation', title: t("8. Cancellation"), content: <P>{t("Subscription management is not operational in this student version. For production deployment, a clearly identified, free electronic cancellation feature must be available, with its steps described here: [TO COMPLETE — effective date, consequences for access, any refund, and contact]. The phrase “cancel at any time” must not be used before this feature is implemented.")}</P> },
    { id: 'retractation', title: t("9. Right of withdrawal"), content: <P>{t("The applicable rules depend on the precise classification of the digital service and when its performance begins. Before any sale, specify the fourteen-day period, standard form, and submission address. If access begins immediately, separately obtain any request for early performance and acknowledgment of loss of the withdrawal right required by law: [TO COMPLETE after legal review].")}</P> },
    { id: 'garanties', title: t("10. Warranties and liability"), content: <P>{t("Applicable statutory warranties for digital services remain due. Procedure for bringing the service into conformity, duration of necessary updates, technical support, and lawful contractual limitations: [TO COMPLETE]. No clause restricts mandatory consumer rights.")}</P> },
    { id: 'reclamations', title: t("11. Complaints and mediation"), content: <P>{t("Complaints must first be sent to [TO COMPLETE — customer service]. If no amicable solution is reached, consumers may refer the matter free of charge to [TO COMPLETE — consumer mediator, address, and website] after following the required preliminary procedure. The European online dispute resolution platform has ceased operating, so no obsolete address should be added.")}</P> },
    { id: 'droit', title: t("12. Governing law and evidence"), content: <P>{t("The contract is governed by French law without depriving consumers of mandatory protections in their country of residence. Electronic records of orders, acceptance, and payments may serve as evidence under the conditions prescribed by law. Competent court and retention period: [TO COMPLETE].")}</P> },
  ];

  return <LegalPageLayout title={t("Terms of Sale and Subscription")} description={t("Contractual information applicable to MealMosaic paid plans.")} sections={sections} />;
}
